services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
