name: TranslateThis
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        working-directory: ./app
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql
        run: composer install --prefer-dist
      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit
      - run: docker build --target app -t sergeshin/php-composer:1.2 -f ./app/Dockerfile .
      - run: docker build -t sergeshin/nginx-php:1.0 -f /nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sergeshin/php-composer:1.2
      - run: docker push sergeshin/nginx-php:1.0
